[phases.setup]
nixPkgs = ["python310", "libGL", "libGLU", "ffmpeg", "git"]

[phases.install]
cmds = [
  "python3.10 -m pip install --upgrade pip",
  "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
