[phases.setup]
nixPkgs = ["python310Full", "libGL", "libGLU", "ffmpeg", "git"]

[phases.install]
# Temporarily remove the upgrade line to see if the base pip works
cmds = [
  "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
