[phases.setup]
nixPkgs = ["python310", "ffmpeg", "git", "libGL", "libGLU"]

[phases.install]
cmds = [
  "python3.10 -m ensurepip",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
